-- MySQL Script generated by MySQL Workbench
-- Sun Apr 18 13:03:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mina_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mina_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mina_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `mina_app` ;

-- -----------------------------------------------------
-- Table `mina_app`.`alphabet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mina_app`.`alphabet` (
  `alphabet_id` INT NOT NULL,
  `katakana` VARCHAR(255) NULL DEFAULT NULL,
  `hiragana` VARCHAR(255) NULL DEFAULT NULL,
  `KatakanaWrite` VARCHAR(255) NULL DEFAULT NULL,
  `HiraganaWrite` VARCHAR(255) NULL DEFAULT NULL,
  `example` VARCHAR(255) NULL DEFAULT NULL,
  `romaji` VARCHAR(255) NULL DEFAULT NULL,
  `voice` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`alphabet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mina_app`.`tai_khoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mina_app`.`tai_khoan` (
  `ten_dang_nhap` VARCHAR(200) NOT NULL,
  `psw` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ten_dang_nhap`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mina_app`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mina_app`.`unit` (
  `unit_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `kotoba` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mina_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mina_app`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `ten_dang_nhap` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `psw` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mina_app`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mina_app`.`word` (
  `word_id` INT NOT NULL AUTO_INCREMENT,
  `index` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `mean` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `kanji` VARCHAR(255) NULL DEFAULT NULL,
  `romaji` VARCHAR(255) NOT NULL,
  `kanOto` VARCHAR(255) NULL DEFAULT NULL,
  `voice` VARCHAR(255) NULL DEFAULT NULL,
  `unit_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`word_id`),
  INDEX `FK_19da7a9da0f75b4159fca7361d7` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `FK_19da7a9da0f75b4159fca7361d7`
    FOREIGN KEY (`unit_id`)
    REFERENCES `mina_app`.`unit` (`unit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2196
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
