-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 11:32:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nihongodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nihongodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nihongodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `nihongodb` ;

-- -----------------------------------------------------
-- Table `nihongodb`.`bai_hoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nihongodb`.`bai_hoc` (
  `IDbai_hoc` INT NOT NULL AUTO_INCREMENT,
  `IDkhoa_hoc` VARCHAR(6) NULL DEFAULT NULL,
  `IDnguoi_day` INT NULL DEFAULT NULL,
  `tongDiem` INT NULL DEFAULT NULL,
  `tenBaiHoc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDbai_hoc`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nihongodb`.`khoa_hoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nihongodb`.`khoa_hoc` (
  `IDkhoa_hoc` VARCHAR(6) NOT NULL,
  `tenKH` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDkhoa_hoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nihongodb`.`nguoi_dung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nihongodb`.`nguoi_dung` (
  `IDnguoidung` INT NOT NULL,
  `ten` VARCHAR(45) NOT NULL,
  `chuc_danh` VARCHAR(45) NULL DEFAULT NULL,
  `ngaysinh` DATE NOT NULL,
  `gioi_tinh` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`IDnguoidung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nihongodb`.`quatrinhhoctap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nihongodb`.`quatrinhhoctap` (
  `IDnguoidung` INT NOT NULL,
  `IDbai_hoc` INT NOT NULL,
  `diem` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDnguoidung`, `IDbai_hoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nihongodb`.`tai_khoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nihongodb`.`tai_khoan` (
  `ten_dangnhap` INT NOT NULL,
  `IDnguoidung` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ten_dangnhap`),
  UNIQUE INDEX `ten_dangnhap_UNIQUE` (`ten_dangnhap` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nihongodb`.`tham_gia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nihongodb`.`tham_gia` (
  `IDnguoidung` INT NOT NULL,
  `IDkhoa_hoc` VARCHAR(6) NOT NULL,
  `ngayThamGia` DATE NULL DEFAULT NULL,
  `ngayHoanThanh` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IDnguoidung`, `IDkhoa_hoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
